version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: questionnaire
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  db:
    image: mysql:8.0.19
    container_name: questionnaire-database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
    volumes:
      - questionnaire-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  questionnaire-data:
